POST http://localhost:3000/comics/addList/1017100
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Ik9tYXIiLCJzdWIiOiI2NmI2MGQ1MzI1MDM5MmQyODQwMDlmYjciLCJpYXQiOjE3MjMyMDc5MTksImV4cCI6MTcyMzIxMTUxOX0.d1hTcMG7R1R9XiDddtwi6c8AppzcbTrpFg24pvRbYZo 

{
  "nameList": "My ListHeroes"
}