POST http://localhost:3000/user/created
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MjMyMDY1NTYsImV4cCI6MTcyMzIxMDE1Nn0.y1sYgEARR6CHrSoucs94PwrP5Gv2VYQbQDp6W2LN220

{
  "name": "Marhta",
  "document": "45464101",
  "email": "homartica@gmail.com"
}