GET http://localhost:3000/comics/comic/66ae2e0c64f49dd3c6c575e0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6Ik9tYXIiLCJzdWIiOiI2NjljNjlhNzlhN2E4NWMzODNlMmIzMDQiLCJpYXQiOjE3MjI3Mzk0MDYsImV4cCI6MTcyMjc0MzAwNn0.DjjKcLCAKA6ohHcG8rXOw5Y9QzusqEv-cnTN7lRVNa0