GET http://localhost:3000/comics/mongodb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkNhbWlsbyBBbmRyZXMiLCJzdWIiOiI2NjljNmFiYjlhN2E4NWMzODNlMmIzMDYiLCJpYXQiOjE3MjI5NjE1MDksImV4cCI6MTcyMjk2NTEwOX0.tzJ7uNC6rsA7HRGKVfLV-e4CZx_R5OZPaUn65zN-Mfc